- name: creating new user
  hosts: n2
  become: yes

  roles:
    - name: usercreation
      tags:
        - usercreation

    - name: packageinstallation
      tags:
        - packageinstallation

    - name: fileoperation
      tags:
        - fileoperation

    - name: directory
      tags:
        - directory

    - name: cron
      tags:
        - cron

    - name: sql
      tags:
        - sql

    - name: java
      tags:
        - java

    - name: python
      tags:
        - python
