- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common
        - ca-certificates
        - lsb-release
        - apt-transport-https
    - name: Adding Ondrej PPA to system
      command: "LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php"
    - name: Install required python version
      apt:
        name: php5.6 
