- name: Executing main playbook
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
  roles:
  - name: nginx
    tags: 
      - nginx
  - name: tomcat
    tags: 
      - tomcat_setup
  - name: Dotnet
    tags: 
      - dotnet
  - name: php
    tags: 
      - php

