---
- name: Run a Command Only Once
  hosts: all
  tasks:
    - name: Execute the command (only once)
      command: ls
      register: command_output
      ignore_errors: true
      run_once: true

    - name: Check the output
      set_fact:
        command_executed: "{{ command_output.rc == 0 }}"

    - name: Display a debug message
      debug:
        msg: "Command already executed, skipping."
      when: command_executed

    - name: Execute the command if not already executed
      command: ls
      when: not command_executed

