- name: Create a user
  user:
    name: tomcat
    state: present
    shell: /bin/bash  
    createhome: yes
    password: "{{ 'tomcat' | password_hash('sha512') }}"
- name: create a group
  group:
    name: tomcat
    state: present
