- name: Create a user
  user:
    name: tomcat
    state: present
    shell: /bin/bash  
    createhome: yes
    password: "{{ 'tomcat' | password_hash('sha512') }}"
- name: create a group
  group:
    name: tomcat
    state: present
- name: install java
  apt:
    name: default-jdk
    state: present
- name: download & unarchive tomcat10 
  unarchive:
    src: "{{ url }}"
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]