- name: Create a user
  user:
    name: tomcat
    state: present
    shell: /bin/bash  
    createhome: yes
    password: "{{ 'tomcat' | password_hash('sha512') }}"
- name: create a group
  group:
    name: tomcat
    state: present
- name: install java
  apt:
    name: default-jdk
    state: present
- name: extract tar file in remote machine
  unarchive: 
    src: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz"
    dest: /opt/
    remote_src: False