---
- name: installing the following packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - software-properties-common

- name: Ensure the directory exists
  file:
    path: /usr/share/keyrings
    state: directory

- name: Download Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'

- name: Add Grafana repository to sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/grafana.list
    line: 'deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main'
    create: yes

- name: update package and install Grafana
  apt:
    update_cache: yes
    name: grafana

