- name: Create document root directory for virtual hosts
  file:
    path: "{{ item.document_root }}"
    state: directory
  with_items: "{{ apache_vhosts }}"

- name: Create virtual host configuration files
  template:
    src: virtualhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
  notify: Reload Apache
  with_items: "{{ apache_vhosts }}"
