- name: Update apt cache
  apt:
    update_cache: yes

- name: install redis
  apt:
    name: redis
    state: present
- name: start redis server
  service:
    name: redis-server
    state: restarted
